// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbbumhveorwmgenvooli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiYnVtaHZlb3J3bWdlbnZvb2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTEzMDksImV4cCI6MjA3MDkyNzMwOX0.18ANaVfcPgAgMfHurzv-Iqdit6RkZUKDpvRHu5BVDjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});